version: '3'
services:
  mule-app:
    build:
     context: .
     dockerfile: dockerfile
    image: mulesoft:docker
    container_name: mulesoft-docker
    volumes:
    - ./apps:/opt/mule/apps
    - ./conf:/opt/mule/conf
    - ./logs:/opt/mule/logs
    ports:
     - 8181:8181
     
